---
# These tasks install apache and the php modules.
#comenzamos la instalación propiamente dicha de nuestro nuevo php.
#Instalamos los requerimientos y paquetes a utilizar 
#Instalamos apache y inicimaos el servicio 

- name: Instalando PHP y modulos requeridos
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - php7.0-json
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-xml
    - php7.0-mysql
    - libapache2-mod-php7.0
    - git


- name: Instalando Apache
  apt:
    name: apache2
    state: present


- name: Iniciando servicio Apache
  service:
    name: apache2
    state: started
    enabled: yes
