---
# These tasks install http and the php modules.
#Cambiar yum por apt
#lib-semanage es para centos ubuntu es python-semanage y
#libselinux-python por python-selinux
#- name: Install http and php etc
# apt: name={{ item }} state=present update_cache=yes
 # with_items:
  # - httpd
   #- php
   #- php-mysql
  # - git
  # - libsemanage-python
   #- libselinux-python

#notify: restart iptables

#- name: http service state
# service: name=httpd state=started enabled=yes

#- name: Configure SELinux to allow httpd to connect to remote database
 # seboolean: name=httpd_can_network_connect_db state=true persistent=yes
 # when: sestatus.rc != 0
 
#Instalamos apache y inicimaos el servicio 

- name: Instalando Apache
  apt:
    name: apache2
    state: present


- name: Iniciando servicio Apache
  service:
    name: apache2
    state: started
    enabled: yes
